Переклад сторінки template-syntax.md.
vuejs-translations/docs-uk pull request #100
Opened 2022-10-16 20:27 UTC by dddarkasss

## Опис проблеми

## Запропоноване вирішення

## Додаткова інформація

2022-10-17 07:36 UTC, matrunchyk commented on src/guide/essentials/template-syntax.md
> +Vue використовує синтаксис шаблону на основі HTML, який дозволяє нам декларативно привʼязати відрендерений DOM до даних екземпляра компонента нижчого рівня. Усі шаблони Vue синтаксично коректні HTML,
Неконсистетно: тут ти пишеш "шаблона", а в заголовку — "шаблону".

2022-10-17 07:38 UTC, matrunchyk commented on src/guide/essentials/template-syntax.md
>    const rawHtml = '<span style="color: red">This should be red.</span>'
Неперекладений рядок

2022-10-17 07:41 UTC, matrunchyk commented on src/guide/essentials/template-syntax.md
> +:::warning Попередження безпеки
XSS вразливостей

2022-10-17 07:41 UTC, matrunchyk commented on src/guide/essentials/template-syntax.md
> +Динамічний рендеринг довільного HTML-коду на вашому вебсайті може бути дуже небезпечним, оскільки може легко призвести до [XSS vulnerabilities](https://en.wikipedia.org/wiki/Cross-site_scripting). Ви
XSS вразливостей

2022-10-17 07:46 UTC, matrunchyk commented on src/guide/essentials/template-syntax.md
>  <!-- This will trigger a compiler warning. -->
неперекладений текст

2022-10-17 07:46 UTC, matrunchyk commented on src/guide/essentials/template-syntax.md
>  <p v-if="seen">Now you see me</p>
Неперекладений текст

2022-10-17 07:46 UTC, matrunchyk requested changes
See above

2022-10-17 09:30 UTC, nazar1ua requested changes

2022-10-17 09:30 UTC, nazar1ua commented on src/guide/essentials/template-syntax.md
> +[Булеві атрибути](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes) це атрибути, які можуть вказувати на значення true/false за допомогою їх присутності в елементі.
```suggestion
[Логічні атрибути](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes) це атрибути, які можуть вказувати на значення true/false за допомогою їх присутності в елементі. Наприклад, [`disabled`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled) є одним із найбільш часто використовуваних логічних атрибутів.
```

2022-10-17 09:30 UTC, nazar1ua commented on src/guide/essentials/template-syntax.md
>  <div :id="`list-${id}`"></div>
Трохи вище можна перекласти
```vue-html
{{ ok ? 'ТАК' : 'НІ' }}
```

2022-10-17 09:30 UTC, nazar1ua commented on src/guide/essentials/template-syntax.md
>  <a @click="doSomething"> ... </a>
В рядку 199 неперекладений текст

2022-10-17 09:30 UTC, nazar1ua commented on src/guide/essentials/template-syntax.md
> +
Лишній рядок
```suggestion
```

2022-10-17 09:30 UTC, nazar1ua commented on src/guide/essentials/template-syntax.md
> +Зауважте, що існують певні обмеження на вираз аргументу,
```suggestion
Зауважте, що існують певні обмеження для виразу аргументу,
```

2022-10-17 09:30 UTC, nazar1ua commented on src/guide/essentials/template-syntax.md
>  ```
У рядку 217 неперекладений текст

2022-10-17 09:30 UTC, nazar1ua commented on src/guide/essentials/template-syntax.md
> +Тут `attributeName` динамічно обчислюватиметься як вираз JavaScript, а його оцінене значення використовуватиметься як кінцеве значення для аргументу. Наприклад, якщо ваш екземпляр компонента має влас
```suggestion
Тут `attributeName` динамічно обчислюватиметься як вираз JavaScript, а його оцінене значення використовуватиметься як кінцеве значення для аргументу. Наприклад, якщо ваш екземпляр компонента має змінну `attributeName`, значення якої дорівнює `"href"`, тоді це прив'язування буде еквівалентним `v-bind:href`.
```

2022-10-17 09:30 UTC, nazar1ua commented on src/guide/essentials/template-syntax.md
> +Тут `attributeName` динамічно обчислюватиметься як вираз JavaScript, а його оцінене значення використовуватиметься як кінцеве значення для аргументу. Наприклад, якщо ваш екземпляр компонента має влас
Я думаю, так буде набагато зрозуміліше

2022-10-17 09:30 UTC, nazar1ua commented on src/guide/essentials/template-syntax.md
>  <a @[eventName]="doSomething">
У рядку 228 неперекладений текст

2022-10-18 20:02 UTC, matrunchyk commented on src/guide/essentials/template-syntax.md
> +[Булеві атрибути](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes) це атрибути, які можуть вказувати на значення true/false за допомогою їх присутності в елементі.
Булевий тип - це теж вірний переклад насправді

2022-10-18 20:03 UTC, matrunchyk submitted a review, later dismissed

2022-10-18 20:36 UTC, matrunchyk commented on src/guide/essentials/template-syntax.md
> +Vue використовує синтаксис шаблону на основі HTML, який дозволяє нам декларативно привʼязати відрендерений DOM до даних екземпляра компонента нижчого рівня. Усі шаблони Vue синтаксично коректні HTML,
```suggestion
Vue використовує синтаксис шаблона на основі HTML, який дозволяє нам декларативно привʼязати відрендерений DOM до даних екземпляра компонента нижчого рівня. Усі шаблони Vue синтаксично коректні HTML, які можуть бути проаналізовані браузерами, сумісними зі специфікаціями, і парсерами HTML.
```

2022-10-18 20:36 UTC, matrunchyk commented on src/guide/essentials/template-syntax.md
>  <span>Message: {{ msg }}</span>
```suggestion
<span>Повідомлення: {{ msg }}</span>
```

2022-10-18 20:37 UTC, matrunchyk commented on src/guide/essentials/template-syntax.md
> +Вміст `span` буде замінено на значення властивості `rawHtml`, інтерпретоване як звичайний HTML - дані прив'язування ігноруються. Зверніть увагу, що ви не можете використовувати `v-html` для створення
```suggestion
Вміст `span` буде замінено на значення властивості `rawHtml`, інтерпретоване як звичайний HTML - дані прив'язування ігноруються. Зверніть увагу, що ви не можете використовувати `v-html` для створення частин шаблона, оскільки Vue не є системою створення шаблонів на основі рядків. Натомість компоненти є основними одиницями для повторного використання та композиції інтерфейсу користувача.
```

2022-10-18 20:38 UTC, matrunchyk commented on src/guide/essentials/template-syntax.md
> +Глобальні елементи, явно не включені до списку, наприклад властивості, прикріплені користувачем у `window`, не будуть доступні у виразах шаблону. Однак ви можете явно визначити додаткові глобальні дл
```suggestion
Глобальні елементи, явно не включені до списку, наприклад властивості, прикріплені користувачем у `window`, не будуть доступні у виразах шаблона. Однак ви можете явно визначити додаткові глобальні для всіх виразів Vue, додавши їх до [`app.config.globalProperties`](/api/application.html#app-config-globalproperties).
```

2022-10-18 20:38 UTC, matrunchyk approved these changes

2022-10-19 20:27 UTC, matrunchyk approved these changes

2022-10-19 20:46 UTC, nazar1ua approved these changes
👍🏻

2022-10-19 20:49 UTC, merged