add translation for tooling page
vuejs-translations/docs-uk pull request #113
Opened 2022-10-21 09:06 UTC by winato

## Опис проблеми

## Запропоноване вирішення

## Додаткова інформація

2022-10-21 09:07 UTC, winato commented on src/guide/scaling-up/tooling.md
> +[Vite](https://vitejs.dev/) — це легкий і швидкий інструмент для створення з першокласною підтримкою Vue SFC. Його створив Еван Ю, який також є автором Vue!
```suggestion
[Vite](https://vitejs.dev/) — це легкий і швидкий інструмент для розробки з першокласною підтримкою Vue SFC. Його створив Еван Ю, який також є автором Vue!
```

2022-10-21 11:29 UTC, matrunchyk commented on src/guide/scaling-up/tooling.md
> +  - Середовище, схоже на IDE, у вебпереглядачі працює фактичний сервер Vite dev
```suggestion
  - Середовище, схоже на IDE, що запускає фактичний сервер розробки Vite у браузері
```
Неправильна побудова речення. Гугл?

2022-10-21 11:31 UTC, matrunchyk commented on src/guide/scaling-up/tooling.md
> +  - Призначений для перевірки результатів компіляції компонентів
@winato прошу перечитувати гугл переклад. А краще — взагалі його використовувати по мінімуму, якщо можливо.
```suggestion
  - Призначена для перевірки результатів компіляції компонентів
```

2022-10-21 11:33 UTC, matrunchyk commented on src/guide/scaling-up/tooling.md
> +Також рекомендується використовувати ці онлайн-пісочниця, щоб надавати репродукції під час повідомлення про помилки.
ці онлайн-пісочниця
надавати репродукції

2022-10-21 11:34 UTC, matrunchyk commented on src/guide/scaling-up/tooling.md
> +Обидва онлайн-пісочниці, згадані вище, також підтримують завантаження файлів як проект Vite.
обидва пісочниці?

2022-10-21 11:35 UTC, matrunchyk requested changes
Не став робити подальше рев'ю. Прошу власноруч перечитати всі тексти і внести правки.

2022-10-24 09:34 UTC, matrunchyk commented on src/guide/scaling-up/tooling.md
> +## Лінтинг {#linting}
```suggestion
## Статичний аналіз {#linting}
```

2022-10-24 09:34 UTC, matrunchyk commented on src/guide/scaling-up/tooling.md
> +Команда Vue підтримує [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue), плагін [ESLint](https://eslint.org/), який підтримує спеціальне лінтування одно-файлових компонентів.
```suggestion
Команда Vue підтримує [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue), плагін [ESLint](https://eslint.org/), який підтримує статичний аналіз спеціально для одно-файлових компонентів.
```

2022-10-24 09:35 UTC, matrunchyk commented on src/guide/scaling-up/tooling.md
> +Користувачі, які раніше використовували Vue CLI, можуть звикнути до конфігурації лінтера за допомогою Webpack. Однак, якщо використовується налаштування збірки на основі Vite, наша загальна рекоменда
```suggestion
Користувачі, які раніше використовували Vue CLI, можуть звикнути до конфігурації статичного аналізатора за допомогою Webpack. Однак, якщо використовується налаштування збірки на основі Vite, наша загальна рекомендація:
```

2022-10-24 09:35 UTC, matrunchyk commented on src/guide/scaling-up/tooling.md
> +2. Налаштуйте розширення IDE ESLint, наприклад [ESLint для VSCode](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), щоб ви отримували повідомлення від лінтера прямо у своє
```suggestion
2. Налаштуйте розширення IDE ESLint, наприклад [ESLint для VSCode](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), щоб ви отримували повідомлення від статичного аналізатора прямо у своєму редакторі під час розробки. Це також дозволяє уникнути зайвих витрат на перевірку під час запуску сервер розробки.
```

2022-10-24 09:36 UTC, matrunchyk commented on src/guide/scaling-up/tooling.md
> +3. Запустіть ESLint як частину команди виробничої збірки, щоб отримати повний відгук лінтера перед публікацією.
```suggestion
3. Запустіть ESLint як частину команди виробничої збірки, щоб отримати повний звіт від статичного аналізатора перед публікацією.
```

2022-10-24 09:36 UTC, matrunchyk commented on src/guide/scaling-up/tooling.md
> +4. (Необов’язково) Налаштуйте такі інструменти, як [lint-staged](https://github.com/okonet/lint-staged), щоб автоматично змінювати файли lint під час git-коміту.
```suggestion
4. (Необов’язково) Налаштуйте такі інструменти, як [lint-staged](https://github.com/okonet/lint-staged), щоб автоматично змінювати статично проаналізовані файли під час git коміту.
```

2022-10-24 09:37 UTC, matrunchyk commented on src/guide/scaling-up/tooling.md
> +- Розширення VSCode [Volar](https://github.com/johnsoncodehk/volar) одразу забезпечує форматування для одно-файлових компонентів Vue.
```suggestion
- Розширення VSCode [Volar](https://github.com/johnsoncodehk/volar) одразу забезпечує форматування для однофайлових компонентів Vue.
```

2022-10-24 09:43 UTC, matrunchyk requested changes

2022-10-24 09:43 UTC, matrunchyk commented on src/guide/scaling-up/tooling.md
> +- Крім того, [Prettier](https://prettier.io/) забезпечує вбудовану підтримку форматування одно-файлових компонентів Vue.
```suggestion
- Крім того, [Prettier](https://prettier.io/) забезпечує вбудовану підтримку форматування однофайлових компонентів Vue.
```

2022-10-24 09:43 UTC, matrunchyk commented on src/guide/scaling-up/tooling.md
> +Цей пакет є частиною основного моно-репозиторію Vue і завжди публікується з тією ж версією, що й основний пакет `vue`. Він включений як залежний від основного пакета `vue` і проксі-сервер у `vue/comp
```suggestion
Цей пакет є частиною основного моно репозиторію Vue і завжди публікується з тією ж версією, що й основний пакет `vue`. Він включений як залежний від основного пакета `vue` і проксі сервер у `vue/compiler-sfc`, тому вам не потрібно встановлювати його окремо.
```

2022-10-24 09:43 UTC, matrunchyk commented on src/guide/scaling-up/tooling.md
> +Сам пакет надає утиліти нижчого рівня для обробки одно-файлових компонентів Vue і призначений лише для авторів інструментів, яким потрібно підтримувати одно-файлові компоненти Vue у користувацьких ін
```suggestion
Сам пакет надає утиліти нижчого рівня для обробки однофайлових компонентів Vue і призначений лише для авторів інструментів, яким потрібно підтримувати однофайлові компоненти Vue у користувацьких інструментах.
```

2022-10-24 09:43 UTC, matrunchyk commented on src/guide/scaling-up/tooling.md
> +Офіційний плагін, який забезпечує підтримку одно-файлових компонентів Vue у Vite.
```suggestion
Офіційний плагін, який забезпечує підтримку однофайлових компонентів Vue у Vite.
```

2022-10-24 09:43 UTC, matrunchyk commented on src/guide/scaling-up/tooling.md
> +Офіційний завантажувач, який забезпечує підтримку одно-файлових компонентів Vue з Webpack. Якщо ви використовуєте Vue CLI, також перегляньте [документацію про зміну параметрів `vue-loader` у Vue CLI]
```suggestion
Офіційний завантажувач, який забезпечує підтримку однофайлових компонентів Vue з Webpack. Якщо ви використовуєте Vue CLI, також перегляньте [документацію про зміну параметрів `vue-loader` у Vue CLI](https://cli.vuejs.org/guide/webpack.html#modifying-options-of-a-loader) .
```

2022-10-24 09:43 UTC, matrunchyk commented on src/guide/scaling-up/tooling.md
> +## Інші онлайн-пісочниці {#other-online-playgrounds}
```suggestion
## Інші онлайн пісочниці {#other-online-playgrounds}
```

2022-10-24 09:43 UTC, matrunchyk commented on src/guide/scaling-up/tooling.md
> +Вам не потрібно нічого встановлювати на свій комп’ютер, щоб випробувати одно-файлові компоненти Vue – існують онлайн-пісочниці, які дозволяють робити це прямо у браузері:
```suggestion
Вам не потрібно нічого встановлювати на свій комп’ютер, щоб випробувати однофайлові компоненти Vue – існують онлайн пісочниці, які дозволяють робити це прямо у браузері:
```

2022-10-24 09:43 UTC, matrunchyk commented on src/guide/scaling-up/tooling.md
> +Також рекомендується використовувати ці онлайн-пісочниці, для надання репродукцій при повідомленні про помилки.
```suggestion
Також рекомендується використовувати ці онлайн пісочниці, для надання репродукцій при повідомленні про помилки.
```

2022-10-24 21:39 UTC, matrunchyk approved these changes

2022-10-25 07:02 UTC, merged