add translation for reacivity in depth page
vuejs-translations/docs-uk pull request #122
Opened 2022-10-26 13:00 UTC by winato

## Опис проблеми

## Запропоноване вирішення

## Додаткова інформація

2022-10-26 13:14 UTC, winato commented on src/guide/extras/reactivity-in-depth.md
> +Однією з найбільш відмінних рис Vue є ненав'язлива система реактивності. Компонентний стан складається з реактивних об'єктів JavaScript. Коли ви змінюєте їх, вид оновлюється. Це робить управління ста
```suggestion
Однією з найбільш відмінних рис Vue є ненав'язлива система реактивності. Стан компонента складається з реактивних об'єктів JavaScript. Коли ви змінюєте їх, вид оновлюється. Це робить управління станом простим та інтуїтивно зрозумілим, але також важливо розуміти, як це працює, щоб уникнути деяких поширених помилок. У цьому розділі ми збираємося розібратися в деяких деталях нижчого рівня системи реактивності Vue.
```

2022-10-26 13:14 UTC, winato commented on src/guide/extras/reactivity-in-depth.md
> +1. Відстежувати, коли змінна зчитується. Наприклад при обчисленні виразу `A0 + A1` читаються як `A0`, так і `A1`.
```suggestion
1. Відстежувати, коли змінна зчитується. Наприклад, при обчисленні виразу `A0 + A1` читаються як `A0`, так і `A1`.
```

2022-10-26 13:14 UTC, winato commented on src/guide/extras/reactivity-in-depth.md
> +За допомогою хуків життєвого циклу <span class="options-api">`renderTracked`</span> <span class="composition-api">`onRenderTracked`</span> та <span class="options-api">`renderTriggered`</span><span c
```suggestion
За допомогою хуків життєвого циклу <span class="options-api">`renderTracked`</span> <span class="composition-api">`onRenderTracked`</span> та <span class="options-api">`renderTriggered`</span><span class="composition-api">`onRenderTriggered`</span> ми можемо налагодити залежності, які використовуються під час візуалізації компонента та залежність, яка ініціює оновлення. Обидва хуки отримають подію налагоджувача, яка містить інформацію про відповідну залежність. Рекомендується розмістити оператор `debugger` у зворотних викликах, щоб інтерактивно перевірити залежність:
```

2022-10-29 09:18 UTC, winato commented on src/guide/extras/reactivity-in-depth.md
> +Фактично, це дуже близько до того, як компонент Vue підтримує синхронізацію стану та DOM – кожен екземпляр компонента створює реактивний ефект для візуалізації та оновлення DOM. Звичайно, компоненти
```suggestion
Фактично, це дуже близько до того, як компонент Vue підтримує синхронізацію стану та DOM – кожний екземпляр компонента створює реактивний ефект для візуалізації та оновлення DOM. Звичайно, компоненти Vue використовують набагато ефективніші способи оновлення DOM, ніж `innerHTML`. Це описано в [механізмі рендерингу](./rendering-mechanism).
```

2022-10-29 09:18 UTC, winato commented on src/guide/extras/reactivity-in-depth.md
> +Усі API `ref()`, `computed()` і `watchEffect()` є частиною композиційного АРІ. Якщо ви досі використовували тільки опційний АРІ з Vue, ви помітите, що композиційний АРІ ближче до того, як працює сист
```suggestion
Усі API `ref()`, `computed()` і `watchEffect()` є частинами композиційного АРІ. Якщо ви досі використовували тільки опційний АРІ з Vue, ви помітите, що композиційний АРІ ближче до того, як працює система реактивності Vue під капотом. Насправді у Vue 3 опційний АРІ реалізовано поверх композиційного АРІ. Увесь доступ до властивостей екземпляра компонента (`this`) запускає геттер/сеттер для відстеження реактивності, а такі параметри, як `watch` і `computed`, викликають еквіваленти композиційного АРІ.
```

2022-10-29 09:18 UTC, winato commented on src/guide/extras/reactivity-in-depth.md
> +Чудово, що система реактивності Vue автоматично відстежує залежності, але в деяких випадках ми можемо захотіти з’ясувати, що саме відстежується, або що спричиняє повторне рендеринг компонента.
```suggestion
Чудово, що система реактивності Vue автоматично відстежує залежності, але в деяких випадках ми можемо захотіти з’ясувати, що саме відстежується, або що спричиняє повторний рендеринг компонента.
```

2022-10-29 09:18 UTC, winato commented on src/guide/extras/reactivity-in-depth.md
> +Ми можемо налагодити обчислені властивості, передавши `computed()` другий об’єкт параметрів із зворотними викликами `onTrack` і `onTrigger`:
```suggestion
Ми можемо налагодити обчислювані властивості, передавши `computed()` другий об’єкт параметрів із зворотними викликами `onTrack` і `onTrigger`:
```

2022-10-29 09:18 UTC, winato commented on src/guide/extras/reactivity-in-depth.md
> +// доступ plusOne, має запустити onTrack
```suggestion
// доступ до plusOne, має запустити onTrack
```

2022-10-29 09:18 UTC, winato commented on src/guide/extras/reactivity-in-depth.md
> +Загальна ідея інтеграції системи реактивності Vue із зовнішнім рішенням керування станом полягає у збереженні зовнішнього стану в [`shallowRef`](/api/reactivity-advanced.html#shallowref). Неглибока р
```suggestion
Загальна ідея інтеграції системи реактивності Vue зі зовнішнім рішенням керування станом полягає у збереженні зовнішнього стану в [`shallowRef`](/api/reactivity-advanced.html#shallowref). Неглибока референція є реактивною лише тоді, коли здійснюється доступ до її властивості `.value` - внутрішнє значення залишається недоторканим. Коли зовнішній стан змінюється, змінюється значення референції, щоб запустити оновлення.
```

2022-10-30 18:17 UTC, nazar1ua commented on src/guide/extras/reactivity-in-depth.md
>  [Спробуйте в пісочниці](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHVzZUltbWVyIH0gZnJvbSAnLi9pbW1lci5qcydcbiAgXG5jb25zdCBbaXRlbXMsIHVwZGF0ZUl0ZW1zXSA9IHVzZUltbWVyKFtcbiAg
Ми перекладаємо всі посилання на пісочницю
```suggestion
[Спробуйте в пісочниці](https://sfc.vuejs.org/#eNptVLtu2zAU/RWWS2zAkroVVe00HbO2QBfTgyJRNhOKFEjKcSEY6GPo3i8pstTokG+Q/6iXD8mqHQ0WL3l47rnX56rFH+o63jYUp3iuc8VqgzQ1TX1NBKtqqQxqUaPpbVVRhfaoVLJCV3HCbBzf6ysiECIil0IbtGSGVnqGmrrIDL21wQothuuTpQW39gcewwynKSK4+9Uduqfjz+5w/N4d0OeGEjwLoEIKwBgFe7Cxd9svE/ztno9fgeIbkDwD3Y/uqfvdE6LuD3ISzpnLjGtPTcRqSgQRZSNyw6RARq7X3BUxYaKgu6lPPKpt4spFi+tekouXDr2KbQIo/tXFpksHuSDlPPEth2ZDAMCaAzlECM0b7t6w4gxto1KqBcGT1pc9c/qhIShoY8JnJzjUB0+a80xruNUG9PjwJucsf4DDizoJDont04aEaA9ynZqEMy8wcQrnyUg2hNp84Xbp63eNMXRnooLmUmW2syniTNDIbJRs1pt3fSPcPTzD3nVRldVgLynAl46EhAOoMO37TTAY18YEb4ypdZokusytm+91LNU6gVWsGmFYRWOqq+hOyUftfDsYwfI6Y4xZGlE/rONcVt7nN2/j1/GbpGDaBOMDGZC8r2TR8JNdnZ4EEmypihSFbqpz5v/1nUEvNAZn7l1b/MBBP8Jc1gqy5zSMpDuHaRyGVm8yzuXjR1oOYwuJAUEE3TnMYPVhQO8yTT8Z+C+D2f1Ya7sDVj4xjoAnmJ8MwE38Sk1Ho+E44m3GYRgXvfTJaLf/aijHCEXbl4IvkRJo6XA9YmUbsv8HRK+sqw==)
```

2022-10-30 18:51 UTC, nazar1ua commented on src/guide/extras/reactivity-in-depth.md
> +Використання реактивного ефекту для зміни референції не є найцікавішим випадком - насправді використання обчислюваної властивості робить його більш декларативним:
```suggestion
Використання реактивного ефекту для зміни референції не є найцікавішим випадком - насправді використання обчислюваної властивості робить його більш декларативним:

```

2022-10-31 09:39 UTC, winato commented on src/guide/extras/reactivity-in-depth.md
> +Однією з найбільш відмінних рис Vue є ненав'язлива система реактивності. Стан компонента складається з реактивних об'єктів JavaScript. Коли ви змінюєте їх, вид оновлюється. Це робить управління стано
```suggestion
Однією з найбільш відмінних рис Vue є ненав'язлива система реактивності. Стан компонента складається з реактивних об'єктів JavaScript. Коли ви змінюєте їх, вигляд оновлюється. Це робить управління станом простим та інтуїтивно зрозумілим, але також важливо розуміти, як це працює, щоб уникнути деяких поширених помилок. У цьому розділі ми збираємося розібратися в деяких деталях нижчого рівня системи реактивності Vue.
```

2022-11-05 16:56 UTC, nazar1ua commented on src/guide/extras/reactivity-in-depth.md
> +Всередині `computed` керує визнанням його недійсним і повторним обчисленням за допомогою реактивного ефекту.
```suggestion
Всередині `computed` керує своєю інвалідацією та повторним обчисленням за допомогою реактивного ефекту.
```

2022-11-05 19:50 UTC, nazar1ua requested changes

2022-11-05 19:50 UTC, nazar1ua commented on src/guide/extras/reactivity-in-depth.md
> +## Інтеграція зі зовнішніми системами стану {#integration-with-external-state-systems}
```suggestion
## Інтеграція з зовнішніми системами стану {#integration-with-external-state-systems}
```
[ось джерело](https://ukr-mova.in.ua/library/orfografiya/mulozvuchnist-z,-iz,-zi,-zo.-chastuna-1)

2022-11-05 19:50 UTC, nazar1ua commented on src/guide/extras/reactivity-in-depth.md
> +[Скінченний автомат](https://en.wikipedia.org/wiki/Finite-state_machine) — це модель для опису всіх можливих станів, у яких може перебувати програма, і всіх можливих способів переходу з одного стану
можна додати посилання на українську статтю
```suggestion
[Скінченний автомат](https://uk.wikipedia.org/wiki/Скінченний_автомат) — це модель для опису всіх можливих станів, у яких може перебувати програма, і всіх можливих способів переходу з одного стану в інший. Хоча це може бути надмірним для простих компонентів, це може допомогти зробити складні потоки стану більш надійними та керованими.
```

2022-11-05 19:53 UTC, nazar1ua approved these changes

2022-11-05 19:55 UTC, merged