Переклад: Посібник, крок 6
vuejs-translations/docs-uk pull request #182
Opened 2023-02-17 19:40 UTC by OlesyaKlochko

- [x] Я ознайомлений(а) з [Правилами спільноти](https://github.com/vuejs-translations/docs-uk/wiki/Правила-спільноти) та зобов'язуюсь їх дотримуватись.

2023-02-17 20:40 UTC, matrunchyk commented on src/tutorial/src/step-6/description.md
> +Наразі, демо показує обидва елементи `<h1>` одночасно і кнопка нічого не робить. Спробуйте додати `v-if` та `v-else` директиви і напишіть метод `toggle()` таким чином, щоб кнопка перемикала ці елемен
```suggestion
Наразі, демо показує обидва елементи `<h1>` одночасно, і кнопка нічого не робить. Спробуйте додати директиви `v-if` та `v-else` і напишіть метод `toggle()` таким чином, щоб кнопка перемикала ці елементи.
```

2023-02-18 22:45 UTC, nazar1ua approved these changes

2023-02-18 22:50 UTC, nazar1ua requested changes

2023-02-18 22:50 UTC, nazar1ua commented on src/tutorial/src/step-6/description.md
> +Ми можемо використовувати `v-if` директиву для умовного рендерингу елементу:
```suggestion
Ми можемо використовувати `v-if` директиву для умовного рендерингу елемента:
```

2023-02-18 22:50 UTC, nazar1ua approved these changes

2023-02-18 22:52 UTC, merged