Переклад: Посібник, крок 7
vuejs-translations/docs-uk pull request #183
Opened 2023-02-28 17:56 UTC by OlesyaKlochko

- [x] Я ознайомлений(а) з [Правилами спільноти](https://github.com/vuejs-translations/docs-uk/wiki/Правила-спільноти) та зобов'язуюсь їх дотримуватись.

2023-02-28 18:12 UTC, nazar1ua requested changes

2023-02-28 18:12 UTC, nazar1ua commented on src/tutorial/src/step-7/description.md
> +Ми можемо використовувати дерективу `v-for` для рендерингу списка елементів, основаних на вихідному масиві:
```suggestion
Ми можемо використовувати директиву `v-for` для рендерингу списку елементів на основі вихідного масиву
```

2023-02-28 18:12 UTC, nazar1ua commented on src/tutorial/src/step-7/description.md
> +Тут `todo` це локальна змінна, що представляє собою елемент масиву, над яким відбувається ітерація. Він доступний лише в елементі `v-for` або всередині нього, подібно до області видимості функції.
```suggestion
Тут `todo` — це локальна змінна, що представляє собою елемент масиву, над яким відбувається ітерація. Вона доступна лише в елементі `v-for` або всередині нього, подібно до області видимості функції.
```

2023-02-28 18:12 UTC, nazar1ua commented on src/tutorial/src/step-7/description.md
> +Зверніть увагу, що ми також надаємо кожному об’єкту todo унікальний `id` і прив’язуємо його як <a target="_blank" href="/api/built-in-special-attributes.html#key">спеціальний атрибут `key`</a> для ко
```suggestion
Зверніть увагу, що ми також надаємо кожному об’єкту todo унікальний `id` і прив’язуємо його як <a target="_blank" href="/api/built-in-special-attributes.html#key">спеціальний атрибут `key`</a> для кожного `<li>`. `key` дозволяє Vue правильно переміщувати кожен `<li>` відповідно до позиції його відповідного об’єкта в масиві.
```
мені здається, так буде гарніше

2023-02-28 18:12 UTC, nazar1ua commented on src/tutorial/src/step-7/description.md
> +У нас є простий список завдань - спробуйте реалізувати логіку для методів `addTodo()` та `removeTodo()`, щоб він запрацював!
```suggestion
У нас є простий список завдань — спробуйте реалізувати логіку для методів `addTodo()` та `removeTodo()`, щоб він запрацював!
```

2023-02-28 18:12 UTC, nazar1ua commented on src/tutorial/src/step-7/description.md
> +Більш детально про `v-for` в <a target="_blank" href="/guide/essentials/list.html">гіді про рендеринг списків</a>.
```suggestion
Більш детально про `v-for` у <a target="_blank" href="/guide/essentials/list.html">гіді про рендеринг списків</a>.
```

2023-02-28 18:51 UTC, matrunchyk commented on src/tutorial/src/step-7/description.md
> +Зверніть увагу, що ми також надаємо кожному об’єкту todo унікальний `id` і прив’язуємо його як <a target="_blank" href="/api/built-in-special-attributes.html#key">спеціальний атрибут `key`</a> для ко
accurately - точно

2023-02-28 18:52 UTC, matrunchyk approved these changes

2023-02-28 21:31 UTC, OlesyaKlochko commented on src/tutorial/src/step-7/description.md
> +Зверніть увагу, що ми також надаємо кожному об’єкту todo унікальний `id` і прив’язуємо його як <a target="_blank" href="/api/built-in-special-attributes.html#key">спеціальний атрибут `key`</a> для ко
залишаємо тоді 'точно'?

2023-02-28 21:34 UTC, matrunchyk commented on src/tutorial/src/step-7/description.md
> +Зверніть увагу, що ми також надаємо кожному об’єкту todo унікальний `id` і прив’язуємо його як <a target="_blank" href="/api/built-in-special-attributes.html#key">спеціальний атрибут `key`</a> для ко
Так, я б лишив.

valid, correct - правильно, вірно
accurate, precise - точно, виважено

cc @nazar1ua

2023-03-01 10:26 UTC, nazar1ua commented on src/tutorial/src/step-7/description.md
> +Зверніть увагу, що ми також надаємо кожному об’єкту todo унікальний `id` і прив’язуємо його як <a target="_blank" href="/api/built-in-special-attributes.html#key">спеціальний атрибут `key`</a> для ко
якщо дослівно, то _точно_ правильно, але якщо брати до уваги контекст, то _правильно_ мені здається милозвучнішим

2023-03-01 10:27 UTC, nazar1ua approved these changes

2023-03-01 10:28 UTC, merged