Translation for /guide/components/registration.md
vuejs-translations/docs-uk pull request #70
Opened 2022-10-10 15:09 UTC by winato

## Опис проблеми

## Запропоноване вирішення

## Додаткова інформація

2022-10-10 16:42 UTC, nazar1ua commented
@winato ознайомся, будь ласка, з [правилами перекладу](https://github.com/vuejs-translations/guidelines#readme)

2022-10-10 16:58 UTC, winato commented
> @winato ознайомся, будь ласка, з [правилами перекладу](https://github.com/vuejs-translations/guidelines#readme)

Що саме не відповідає цим правилам? 🙂

2022-10-10 19:12 UTC, nazar1ua commented
> > @winato ознайомся, будь ласка, з [правилами перекладу](https://github.com/vuejs-translations/guidelines#readme)
> 
> Що саме не відповідає цим правилам? 🙂

Заголовки треба робити в такому форматі:
```md
## Заголовок {#heading}
```

2022-10-12 07:22 UTC, winato commented
> > > @winato ознайомся, будь ласка, з [правилами перекладу](https://github.com/vuejs-translations/guidelines#readme)
> > 
> > 
> > Що саме не відповідає цим правилам? 🙂
> 
> Заголовки треба робити в такому форматі:
> 
> ```lisp
> ## Заголовок {#heading}
> ```

Дякую. Запушив фікс.

2022-10-12 07:29 UTC, nazar1ua requested changes
Декілька виправлень

2022-10-12 07:29 UTC, nazar1ua commented on src/guide/components/registration.md
> +Ми можемо зробити компоненти глобально доступними в [додатоку Vue](/guide/essentials/application.html) за допомогою методу `app.component()`:
```suggestion
Ми можемо зробити компоненти глобально доступними в [додатку Vue](/guide/essentials/application.html) за допомогою методу `app.component()`:
```

2022-10-12 07:33 UTC, merged