Add translation for props
vuejs-translations/docs-uk pull request #71
Opened 2022-10-12 09:52 UTC by winato

## Опис проблеми

## Запропоноване вирішення

## Додаткова інформація

2022-10-12 10:13 UTC, nazar1ua commented
Треба ще перекласти 31 рядок

2022-10-12 11:18 UTC, matrunchyk commented on src/guide/components/props.md
> +  <VueSchoolLink href="https://vueschool.io/lessons/vue-3-reusable-components-with-props" title="Безкоштовний урок реквізити Vue.js"/>
```suggestion
  <VueSchoolLink href="https://vueschool.io/lessons/vue-3-reusable-components-with-props" title="Безкоштовний урок по реквізитах Vue.js"/>
```

2022-10-12 11:31 UTC, matrunchyk commented on src/guide/components/props.md
> +## Декларація реквізитів {#props-declaration}
```suggestion
## Оголошення реквізитів {#props-declaration}
```

2022-10-12 11:33 UTC, matrunchyk commented on src/guide/components/props.md
> +У компонентах без `<script setup>`, реквізити декларуються за допомогою параметра [`props`](/api/options-state.html#props):
```suggestion
У компонентах без `<script setup>`, реквізити оголошуються за допомогою параметра [`props`](/api/options-state.html#props):
```

2022-10-12 11:34 UTC, matrunchyk commented on src/guide/components/props.md
> +Зауважте, що аргумент, переданий у `defineProps()`, такий самий, як значення, надане параметрам `props`: той самий API параметрів реквізитів використовується між двома стилями декларування.
```suggestion
Зауважте, що аргумент, переданий у `defineProps()`, такий самий, як значення, надане параметрам `props`: той самий API параметрів реквізитів використовується між двома стилями оголошення.
```

2022-10-12 11:44 UTC, matrunchyk commented on src/guide/components/props.md
> +Реквізити декларуються за допомогою параметра [`props`](/api/options-state.html#props):
```suggestion
Реквізити оголошуються за допомогою параметра [`props`](/api/options-state.html#props):
```

2022-10-12 11:45 UTC, matrunchyk commented on src/guide/components/props.md
> +На додаток до декларації реквізитів за допомогою масиву строк, ми також можемо використовувати синтаксис об’єкта:
```suggestion
На додаток до оголошення реквізитів за допомогою масиву рядкових величин, ми також можемо використовувати синтаксис об’єкта:
```

2022-10-12 11:46 UTC, matrunchyk commented on src/guide/components/props.md
> +Для кожної властивості, в синтаксисі оголошення об’єкта, ключ — це ім’я властивості, тоді як значення має бути функцією конструктора очікуваного типу.
```suggestion
Для кожної властивості, в синтаксисі оголошення об’єкта, ключ — це ім’я властивості, тоді як значення має бути функцією-конструктором очікуваного типу.
```

2022-10-12 11:49 UTC, matrunchyk commented on src/guide/components/props.md
> +Якщо ви використовуєте TypeScript із `<script setup>`, можна також оголосити реквізити за допомогою анотацій чистого типу:
```suggestion
Якщо ви використовуєте TypeScript із `<script setup>`, можна також оголосити реквізити за допомогою суто анотацій типу:
```

2022-10-12 11:50 UTC, matrunchyk commented on src/guide/components/props.md
> +Технічно ви також можете використовувати camelCase під час передачі реквізитів дочірньому компоненту (за винятком [шаблонів DOM](/guide/essentials/component-basics.html#dom-template-parsing-caveats))
```suggestion
Технічно ви також можете використовувати camelCase під час передачі реквізитів дочірньому компоненту (за винятком [шаблонів DOM](/guide/essentials/component-basics.html#dom-template-parsing-caveats)). Однак, угода передбачає використання kebab-case у всіх випадках для узгодження з атрибутами HTML:
```

2022-10-13 08:31 UTC, matrunchyk commented on src/guide/components/props.md
> +Буде еквівалентно:
```suggestion
Буде еквівалентним до:
```

Оськільки шаблон — чоловічий рід.

2022-10-13 08:33 UTC, matrunchyk commented on src/guide/components/props.md
> +   // обчислена властивість, яка автоматично оновлюється, коли реквізит змінюється
```suggestion
   // обчислювана властивість, яка автоматично оновлюється, коли реквізит змінюється
```

Див. [глосарій](https://github.com/vuejs-translations/docs-uk/wiki/%D0%93%D0%BB%D0%BE%D1%81%D0%B0%D1%80%D1%96%D0%B9#c)

2022-10-13 08:33 UTC, matrunchyk commented on src/guide/components/props.md
> +2. **Реквізит передається як необроблене значення, яке потрібно трансформувати.** У цьому випадку найкраще визначити обчислену властивість за допомогою значення реквізиту:
```suggestion
2. **Реквізит передається як необроблене значення, яке потрібно трансформувати.** У цьому випадку найкраще визначити обчислювану властивість за допомогою значення реквізиту:
```

Див. [глосарій](https://github.com/vuejs-translations/docs-uk/wiki/%D0%93%D0%BB%D0%BE%D1%81%D0%B0%D1%80%D1%96%D0%B9#c)

2022-10-13 08:34 UTC, matrunchyk commented on src/guide/components/props.md
> +       // обчислена властивість, яка автоматично оновлюється, коли реквізит змінюється
```suggestion
       // обчислювана властивість, яка автоматично оновлюється, коли реквізит змінюється
```

Див. [глосарій](https://github.com/vuejs-translations/docs-uk/wiki/%D0%93%D0%BB%D0%BE%D1%81%D0%B0%D1%80%D1%96%D0%B9#c)

2022-10-13 08:36 UTC, matrunchyk commented on src/guide/components/props.md
> +  // Число зі значенням за умовчанням
```suggestion
  // Число зі значенням за замовчуванням
```

2022-10-13 08:41 UTC, matrunchyk commented on src/guide/components/props.md
> +  // Число зі значенням за умовчанням
```suggestion
  // Число зі значенням за промовчанням
```

Microsoft перекладає як ["за промовчаннями"](https://support.microsoft.com/uk-ua/office/%D0%B2%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F-%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D1%8C-%D0%B7%D0%B0-%D0%BF%D1%80%D0%BE%D0%BC%D0%BE%D0%B2%D1%87%D0%B0%D0%BD%D0%BD%D1%8F%D0%BC-%D0%B4%D0%BB%D1%8F-%D0%BF%D0%BE%D0%BB%D1%96%D0%B2-%D1%96-%D0%B5%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D1%96%D0%B2-%D0%BA%D0%B5%D1%80%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F-99508d03-b28b-4057-9652-dac1c4c60d86). Замовчування - дещо негативний відтінок (щось замовчувати, приховувати), тоді як "промовчання" — більш нейтральний.

2022-10-13 08:42 UTC, matrunchyk commented on src/guide/components/props.md
> +  // Об'єкт зі значенням за замовчуванням
```suggestion
  // Об'єкт зі значенням за промовчанням
```

2022-10-13 08:42 UTC, matrunchyk commented on src/guide/components/props.md
> +    // Значення за замовчуванням для об’єктів або масивів мають бути повернуті
```suggestion
    // Значення за промовчанням для об’єктів або масивів мають бути повернуті
```

2022-10-13 08:44 UTC, matrunchyk commented on src/guide/components/props.md
> +    // На відміну від об’єкта чи масиву за замовчуванням, це не фабрична функція – це функція, яка слугуватиме значенням за замовчуванням
```suggestion
    // На відміну від об’єкта чи масиву за промовчанням, це не фабрична функція – це функція, яка слугуватиме значенням за промовчанням
```

2022-10-13 08:44 UTC, matrunchyk commented on src/guide/components/props.md
> +      return 'Функція за замовчуванням'
```suggestion
      return 'Функція за промовчанням'
```

2022-10-13 08:44 UTC, matrunchyk commented on src/guide/components/props.md
> +    // Число зі значенням за умовчанням
```suggestion
    // Число зі значенням за промовчанням
```

2022-10-13 08:45 UTC, matrunchyk commented on src/guide/components/props.md
> +    // Об'єкт зі значенням за замовчуванням
```suggestion
    // Об'єкт зі значенням за промовчанням
```

2022-10-13 08:45 UTC, matrunchyk commented on src/guide/components/props.md
> +      // Значення за замовчуванням для об’єктів або масивів мають бути повернуті
```suggestion
      // Значення за промовчанням для об’єктів або масивів мають бути повернуті
```

2022-10-13 08:45 UTC, matrunchyk commented on src/guide/components/props.md
> +    // Функція зі значенням за замовчуванням
```suggestion
    // Функція зі значенням за промовчанням
```

2022-10-13 08:45 UTC, matrunchyk commented on src/guide/components/props.md
> +      // На відміну від об’єкта чи масиву за замовчуванням, це не фабрична функція – це функція, яка слугуватиме значенням за замовчуванням
```suggestion
      // На відміну від об’єкта чи масиву за замовчуванням, це не фабрична функція – це функція, яка слугуватиме значенням за промовчанням
```

2022-10-13 08:45 UTC, matrunchyk commented on src/guide/components/props.md
> +        return 'Функція за замовчуванням'
```suggestion
        return 'Функція за промовчанням'
```

2022-10-13 08:45 UTC, matrunchyk commented on src/guide/components/props.md
> +- Усі реквізити є необов’язковими за замовчуванням, якщо не вказано `required: true`.
```suggestion
- Усі реквізити є необов’язковими за промовчанням, якщо не вказано `required: true`.
```

2022-10-13 08:48 UTC, matrunchyk commented on src/guide/components/props.md
> +- Якщо `default` значення вказано, воно використовуватиметься, якщо розв’язане значення реквізиту `undefined` - це стосується як випадків, коли реквізит відсутній, так і передається явне значення `un
```suggestion
- Якщо `default` (значення за промовчанням) вказано, воно використовуватиметься, якщо розв’язане значення реквізиту `undefined` - це стосується як випадків, коли реквізит відсутній, так і передається явне значення `undefined`.
```

2022-10-13 08:49 UTC, matrunchyk requested changes
Рев'ю завершив

2022-10-13 09:27 UTC, matrunchyk approved these changes

2022-10-13 12:18 UTC, nazar1ua requested changes

2022-10-13 12:48 UTC, winato commented on src/guide/components/props.md
> +<!-- це вираз JavaScript, а не строка. -->
> Дякую за рев'ю, але багато з цього я ще вчора виправив в цьому [коміті](https://github.com/vuejs-translations/docs-uk/pull/71/commits/6c0e826d9b4ab2d0a0049999e9b32ba33f1ca56f)

2022-10-13 13:00 UTC, nazar1ua approved these changes
Дякую за переклад!

2022-10-13 13:00 UTC, merged